import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: 'docs'}],
  sdkSidebar: [{type: 'autogenerated', dirName: 'sdk'}],
  protocolSidebar: [{type: 'autogenerated', dirName: 'protocol'}],
  communitySidebar: [{type: 'autogenerated', dirName: 'community'}],
  //examplesSidebar: [{type: 'autogenerated', dirName: 'examples'}],
  changelogSidebar: [{type: 'autogenerated', dirName: 'changelog'}],
};

export default sidebars;