import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: 'docs'}],
  sdkSidebar: [{type: 'autogenerated', dirName: 'sdk'}],
  protocolSidebar: [{type: 'autogenerated', dirName: 'protocol'}]
  //examplesSidebar: [{type: 'autogenerated', dirName: 'examples'}]   
};

export default sidebars;